--PPT08.DDL

--p.03
CREATE TABLE ddl_test
(no NUMBER(3), name VARCHAR2(10), birth DATE DEFAULT SYSDATE) TABLESPACE users;

--p.08
CREATE TABLE emp01(empno NUMBER(4),ename VARCHAR2(20),sal NUMBER(7, 2));

--p.09
CREATE TABLE emp02 AS SELECT * FROM emp;

--p.10
CREATE TABLE emp03 AS SELECT empno, ename FROM emp;

--p.11
CREATE TABLE emp05 AS SELECT * FROM emp WHERE deptno=10;

--p.12
CREATE TABLE emp06 AS SELECT * FROM emp WHERE 1=0;

--p.15
ALTER TABLE emp01 ADD(JOB VARCHAR2(9));

--p.17
ALTER TABLE emp01 MODIFY(JOB VARCHAR2(30));

--p.19
ALTER TABLE emp01 DROP COLUMN JOB;

--p.21
DROP TABLE emp01;

--p.23
TRUNCATE TABLE emp02;

--p.24
RENAME emp02 TO TEST;

--p.27
INSERT INTO dept (deptno, dname, loc) VALUES (10,'test','seoul');

--p.28
INSERT INTO emp06 VALUES (NULL, NULL, 'SALSMAN', 30, NULL, NULL, NULL, NULL);

--p.30
CREATE TABLE emp02(empno NUMBER(4) NOT NULL, ename VARCHAR2(10) NOT NULL, job VARCHAR2(9), deptno NUMBER(2));

--p.32
CREATE TABLE emp03(empno NUMBER(4) UNIQUE, ename VARCHAR2(10) NOT NULL, job VARCHAR2(9), deptno NUMBER(2));

--p.35
CREATE TABLE emp04(empno NUMBER(4) CONSTRAINT EMP04_EMPNO_UK UNIQUE, ename VARCHAR2(10) CONSTRAINT EMP04_ENAME_NN NOT NULL, job VARCHAR2(9), deptno NUMBER(2));

--p.37
CREATE TABLE emp05(
empno NUMBER(4) CONSTRAINT EMP05_EMPNO_PK PRIMARY KEY ,
ename VARCHAR2(10) CONSTRAINT EMP05_ENAME_NN NOT NULL,
job VARCHAR2(9),
deptno NUMBER(2)
);

CREATE TABLE emp07(
empno NUMBER(4) CONSTRAINT EMP07_EMPNO_PK PRIMARY KEY,
ename VARCHAR2(10) CONSTRAINT EMP07_ENAME_NN NOT NULL,
sal NUMBER(7, 2) CONSTRAINT EMP07_SAL_CK CHECK(sal BETWEEN 500 AND 5000),
gender VARCHAR2(1) CONSTRAINT EMP07_GENDER_CK CHECK (gender IN('M', 'F')));

CREATE TABLE dept01(
deptno NUMBER(2) PRIMARY KEY,
dname VARCHAR2(14), 
loc VARCHAR2(13) DEFAULT 'SEOUL');

CREATE TABLE emp02(
empno NUMBER(4),
ename VARCHAR2(10) NOT NULL,
job VARCHAR2(9), 
deptno NUMBER(4),
PRIMARY KEY(empno),
UNIQUE(job),
FOREIGN KEY(deptno) REFERENCES DEPT(deptno));

CREATE TABLE emp03( 
empno NUMBER(4) CONSTRAINT EMP03_ENAME_NN NOT NULL,
ename VARCHAR2(10),
job VARCHAR2(9),
deptno NUMBER(4),
CONSTRAINT EMP03_EMPNO_PK PRIMARY KEY(EMPNO),
CONSTRAINT EMP03_JOB_UK UNIQUE(JOB),
CONSTRAINT EMP03_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO));


