--PPT08.테이블 구조 생성, 변경 및 삭제하는 DDL

--p.03
CREATE TABLE ddl_test
(no NUMBER(3), name VARCHAR2(10), birth DATE DEFAULT SYSDATE) TABLESPACE users;

--p.08
CREATE TABLE emp01(empno NUMBER(4),ename VARCHAR2(20),sal NUMBER(7, 2));

--p.09
CREATE TABLE emp02 AS SELECT * FROM emp;

--p.10
CREATE TABLE emp03 AS SELECT empno, ename FROM emp;

--p.11
CREATE TABLE emp05 AS SELECT * FROM emp WHERE deptno=10;

--p.12
CREATE TABLE emp06 AS SELECT * FROM emp WHERE 1=0;

--p.15
ALTER TABLE emp01 ADD(JOB VARCHAR2(9));

--p.17
ALTER TABLE emp01 MODIFY(JOB VARCHAR2(30));

--p.19
ALTER TABLE emp01 DROP COLUMN JOB;

--p.21
DROP TABLE EMP01;

--p.23
TRUNCATE TABLE EMP02;


